feign:
  hystrix:
    enabled: false
  core1.url: http://core1:8090
  auth.url: http://auth:9080
  product.url: http://product:9090

istio:
  blue:
    domain: blue.istio.com
  green:
    domain: green.istio.com