apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: e2e
  namespace: foo
spec:
  match: source.labels["istio"] == "ingressgateway"
  requestHeaderOperations:
  - name: e2e
    values: ["true"]