apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: front
spec:
  host: front
  subsets:
    - name: v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: core1
spec:
  host: core1
  subsets:
    - name: blue
      labels:
        version: v1
    - name: green
      labels:
        version: v2

